[project]
name = "aleo-pyumbral-keys"
version = "0.1.0"
description = "The aleo-pyumbral-keys package"
license = "MIT"

[remote]
author = "[AUTHOR]" # Add your Aleo Package Manager username or team name.
